local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "configuracoes"
    label: "Meus Projetos"
    files:
      - label: "Lista de Projetos"
        name: "projetos"
        file: "src/data/portfolio.json"
        fields:
          - label: "Projetos"
            name: "projetos"
            widget: "list"
            fields:
              - {label: "ID (Identificador único numérico)", name: "id", widget: "number"}
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Descrição", name: "descricao", widget: "text"}
              - {label: "Tecnologias Usadas", name: "tecnologias", widget: "list"}
              - {label: "Link do Projeto", name: "link", widget: "string", required: false}
              - {label: "Imagem de Capa", name: "image", widget: "image", required: false}
